// generated by stringer -type=BlockKind; DO NOT EDIT

package geoip

import "fmt"

const _BlockKind_name = "BlockIPv6BlockIPv4"

var _BlockKind_index = [...]uint8{0, 9, 18}

func (i BlockKind) String() string {
	if i < 0 || i+1 >= BlockKind(len(_BlockKind_index)) {
		return fmt.Sprintf("BlockKind(%d)", i)
	}
	return _BlockKind_name[_BlockKind_index[i]:_BlockKind_index[i+1]]
}
